site_name: Django
nav:
  - ¿Por qué Django? : por_que_django.md
  - 1. Introducción : 01_introduccion.md
  - 2. Configuración Inicial : 02_configuracion_inicial.md
  - 3. Hello World app : 03_hello_world_app.md
  - 4. Pages app : 04_pages_app.md
  - 5. Message Board app : 05_message_board_app.md
  - 6. Blog app : 06_blog_app.md
  - 7. Formularios : 07_formularios.md
  - 8. Cuentas de Usuarios : 08_cuentas_de_usuarios.md
  - 9. Modelo de Usuario Personalizado: 09_modelo_de_usuario_personalizado.md
  - 10. Autenticación de Usuarios: 10_autenticacion_de_usuarios.md
  - 11. Bootstrap: 11_bootstrap.md
  - 12. Cambio y Restauración de Contraseñas: 12_cambio_y_restauracion_de_contrasenas.md
  - 13. Email: 13_email.md
  - 14. Newspaper app: 14_newspaper_app.md
  - 15. Permisos y Autorización: 15_permisos_y_autorizacion.md
  - 16. Comentarios: 16_comentarios.md
theme: readthedocs

plugins:
    - search:
        separator: '[\s\-\.]+'
        lang: es
