site_name: Django
nav:
  - 1. Introducción : 1_introduccion.md
  - 2. Configuración Inicial : 2_configuracion_inicial.md
  - 3. Hello World app : 3_hello_world_app.md
theme: readthedocs

plugins:
    - search:
        separator: '[\s\-\.]+'
        lang: es

